# -*- coding: utf-8 -*-
"""batalhaNavall

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAl_QDbBLiQWb3VHkjEV_8EIRQLxL8Ee
"""

import random

def geraMapa():
    tabuleiro = []
    for i in range(10):
        linha = []
        for j in range(10):
            linha.append('.')
        tabuleiro.append(linha)
    return tabuleiro


def mapa(t):
    print('-', end=' ')
    x = 0

    for i in range(10):
        print(i, end=" ")
    print()

    for i in range(len(t)):
        for j in range(len(t[0])):
            if j == 0:
                print(x, end=" ")
                x += 1
            print(t[i][j], end=" ")
        print()


def portaAvioes(mapa, linha, coluna, posicao):
    if posicao == True:
        for i in range(linha, linha + 5):
            mapa[i][coluna] = 'P'
    else:
        for i in range(coluna, coluna + 5):
            mapa[linha][i] = 'P'
    return mapa


def encouracado(mapa, linha, coluna, posicao):
    if posicao == True:
        for i in range(linha, linha + 4):
            mapa[i][coluna] = 'E'
    else:
        for i in range(coluna, coluna + 4):
            mapa[linha][i] = 'E'
    return mapa


def cruzador(mapa, linha, coluna, posicao):
    if posicao == True:
        for i in range(linha, linha + 3):
            mapa[i][coluna] = 'C'
    else:
        for i in range(coluna, coluna + 3):
            mapa[linha][i] = 'C'
    return mapa


def submarino(mapa, linha, coluna, posicao):
    if posicao == True:
        for i in range(linha, linha + 2):
            mapa[i][coluna] = 'S'
    else:
        for i in range(coluna, coluna + 2):
            mapa[linha][i] = 'S'
    return mapa

def atirar(t, tj):
    cont = 14
    while cont > 0:
      l = int(input('Digite a posição da linha que deseja atirar: '))
      c = int(input('Digite a posição da coluna que deseja atirar: '))
      if tj[l][c] == '.':
          t[l][c] = 'x'
          tj[l][c] = 'x'
          mapa(t)
          print('Você acertou a água!')
      elif tj[l][c] == 'x' or tj[l][c] == 'X':
          mapa(t)
          print('Você já atirou nessa posição!')
      else:
          t[l][c] = 'X'
          tj[l][c] = 'X'
          cont-=1
          mapa(t)
          print("Você acertou uma embarcação!")


def verifica(mapa, tamanho, linha, coluna, posição):
    if posição:
        for i in range(linha, linha + tamanho):
            if mapa[i][coluna] != ".":
                return False
            
    elif not posição:
        for i in range(coluna, coluna + tamanho):
            if mapa[linha][i] != ".":
                return False
    return True

def jogo(mapa):
    for embarcação in range(1, 5):
        if embarcação == 1:
            tamanho = 5
            tipo = "Porta Aviões"
        elif embarcação == 2:
            tamanho = 4
            tipo = "Encouraçado"
        elif embarcação == 3:
            tamanho = 3
            tipo = "Cruzador"
        elif embarcação == 4:
            tamanho = 2
            tipo = "Submarino"
    
        disponivel = False
        linha = coluna = -1
        posição = random.randint(1,2)
        if posição == 1:
            while not disponivel or linha < 0 or linha > 10 - tamanho or coluna < 0 or coluna > 9:
                posição = True
                linha = random.randint(0, 10 - tamanho)
                coluna = random.randint(0, 9)
                if linha >= 0 and linha <= 10 - tamanho and coluna >= 0 and coluna <= 9:
                    disponivel = verifica(mapa, tamanho, linha, coluna, posição)

        else:
            while not disponivel or linha < 0 or linha > 9 or coluna < 0 or coluna > 10 - tamanho:
                posição = False
                linha = random.randint(0, 9)
                coluna = random.randint(0, 10 - tamanho)
                if linha >= 0 and linha <= 9 and coluna >= 0 and coluna <= 10 - tamanho:
                    disponivel = verifica(mapa, tamanho, linha, coluna, posição)
                        
        if embarcação == 1:
            mapa = portaAvioes(mapa, linha, coluna, posição)
        elif embarcação == 2:
            mapa = encouracado(mapa, linha, coluna, posição)
        elif embarcação == 3:
            mapa = cruzador(mapa, linha, coluna, posição)
        else:
            mapa = submarino(mapa, linha, coluna, posição)

    return mapa





def main():
    print('''

  ____ _ _ _ _
 | __ ) __ _| |_ __ _| | |__ __ _ _ __ __ ___ ____ _| |
 | _ \ / _` | __/ _` | | '_ \ / _` | | '_ \ / _` \ \ / / _` | |
 | |_) | (_| | || (_| | | | | | (_| | | | | | (_| |\ V / (_| | |
 |____/ \__,_|\__\__,_|_|_| |_|\__,_| |_| |_|\__,_| \_/ \__,_|_|


  ''')

    t = geraMapa()
    tj = geraMapa()
    mapa(t)
    jogo(tj)
    mapa(tj)

  

  

    atirar(t,tj)
    mapa(tj)


main()